/*
*
* Copyright (c) Tanel Tammet 2004-2021
*
* Contact: tanel.tammet@gmail.com                 
*
* This file is part of GKC
*
* GKC is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* GKC is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with GKC.  If not, see <http://www.gnu.org/licenses/>.
*
*/

 /** @file makeguide.h
 * Guide building generated by a script.
 */


#ifndef DEFINED_MAKEGUIDE_H
#define DEFINED_MAKEGUIDE_H

/* ==== Includes ==== */

#include "glb.h"

/* ==== Protos ==== */

int make_guide(char* buf, int pos, int iteration, int dsecs, int probsize, int eq, int ueq, int queryok, int qp1ok, int qp2ok, int qp3ok, int sineok);

#endif